[package]
name = "memgame"
version = "0.0.1"
description = "Memory Match Game"
keywords = ["gpui"]
categories = ["game"]
homepage = "https://github.com/stormasm/memgame"
repository = "https://github.com/stormasm/memgame"
license = "MIT"
readme = "README.md"
edition = "2024"
resolver = "2"

[dependencies]
anyhow = "1.0.95"
futures = "0.3.31"
gpui = { git = "https://github.com/zed-industries/zed.git", default-features = false, features = [
    "http_client",
    "font-kit",
] }
rand = "0.9.0"
rust-embed = "8.6.0"
smallvec = "1.13.2"
mimalloc = "0.1.43"

[[bin]]
name = "memgame"
path = "src/main.rs"
